name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.5.0
      - name: install kpt and nomos	
        run: |
          gcloud components install kpt nomos --quiet
      - name: vet	
        run: |
          nomos vet --path . --no-api-server-check --source-format unstructured
      - name: kubeval
        if: ${{ always() }}
        run: |
          kpt fn eval . --results-dir tmp --image gcr.io/kpt-fn/kubeval:v0.3 -- strict=true ignore_missing_schemas=true
      - name: get external templates
        if: ${{ always() }}
        run: |
          kpt pkg get https://github.com/mathieu-benoit/acm-workshop-policies templates
      - name: gatekeeper
        if: ${{ always() }}
        run: |
          kpt fn eval . --results-dir tmp --image gcr.io/kpt-fn/gatekeeper:v0.2
